version: "3"
services:

  app:
    build:
      context: .
      dockerfile: ./docker/flask/Dockerfile
    depends_on:
      - postgres
    environment:
      - DB_HOST=postgres
      - DB_PASSWORD=ratestask
      - API_HOST=app
      - PYTHONDONTWRITEBYTECODE=1
    volumes:
      - ./src:/src
      - ./tests:/tests
    ports:
      - "5005:80"
  postgres:
    build:
        context: .
        dockerfile: ./docker/postgres/Dockerfile
    container_name: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=ratestask
    ports:
      - 5432:5432