version: "3"
services:
  postgres:
    build:
        context: .
        dockerfile: Dockerfile
    container_name: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=ratestask
    ports:
      - 5432:5432